validate: lint test

test:
    pytest --cov=hackvr --cov-report=term-missing

lint: lint-codestyle lint-types

lint-codestyle:
    ruff check

lint-types:
    ty check

install:
    python -m pip install -r requirements.txt

package:
    python -m build
